logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.example.library.manager.backend.dao.entity

spring:
  profiles:
    #运行的环境
    active: prd
  application:
    name: library
  datasource:
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: true
  security:
    basic:
      path: /swagger-ui.html
      enabled: true
    user:
      name: ${security.user-name} #账号
      password: ${security.user-password}  #密码
#redis配置，不设置密码
  redis:
      host: ${redis.host}
      port: ${redis.port}
      database: 0
      timeout: ${redis.timemout}
      lettuce:
        pool:
          # 最大阻塞等待时间，负数表示没有限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 5
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中最大连接数，负数表示没有限制
          max-active: 20
jwt:
  secret:
      key: ${jwt.secret-key}
